services:
  bot:
    build: .
    restart: always
    environment:
      - TOKEN=${TOKEN}
      - NGINX_HOST=${NGINX_HOST}
    volumes:
      - ./data:/bot/data
      - ./.env:/bot/.env
    expose:
      - "7111"
    networks:
      - bot_network
    healthcheck:
      test: ["CMD-SHELL", "timeout 5 bash -c 'until curl -f http://localhost:7111/health; do sleep 1; done' || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s

  nginx:
    image: nginx:1.23-alpine
    ports:
      - "80:80"
      - "443:443"
    restart: always
    environment:
      - NGINX_HOST=bot.shasero.ru
    volumes:
      - ./nginx/templates:/etc/nginx/conf.d:rw
      - ./certbot/www:/var/www/certbot:rw
      - ./certbot/conf:/etc/nginx/ssl:ro
    networks:
      - bot_network
    depends_on:
      bot:
        condition: service_healthy

  certbot:
    image: certbot/certbot:v2.5.0
    command: [
      "certonly",
      "--webroot",
      "--webroot-path=/var/www/certbot",
      "--agree-tos",
      "--non-interactive",
      "--email=romaa251205@gmail.com",
      "-d", "bot.shasero.ru",
      "--keep-until-expiring"
    ]
    volumes:
      - ./certbot/www:/var/www/certbot:rw
      - ./certbot/conf:/etc/letsencrypt:rw
    depends_on:
      - nginx
    networks:
      - bot_network

networks:
  bot_network:
    driver: bridge