services:
  bot:
    build: .
    restart: always
    environment:
      - TOKEN=${TOKEN}
      - NGINX_HOST=${NGINX_HOST}
    volumes:
      - ./data:/bot/data
      - ./.env:/bot/.env
    expose:
      - "7111"
    networks:
      - bot_network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:7111/health || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 10s

  nginx:
    image: nginx:1.23-alpine
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - ./nginx/templates:/etc/nginx/conf.d:rw
      - ./certbot/www:/var/www/certbot:rw
      - ./certbot/conf:/etc/letsencrypt:rw
    networks:
      - bot_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/.well-known/acme-challenge/"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    depends_on:
      bot:
        condition: service_healthy

  certbot:
    image: certbot/certbot:v2.5.0
    command: [
      "certonly",
      "--webroot",
      "--webroot-path=/var/www/certbot",
      "--email=romaa251205@gmail.com", 
      "--agree-tos",
      "--no-eff-email",
      "--force-renewal",
      "-d", "bot.shasero.ru",
      "--quiet"
    ]
    volumes:
      - ./certbot/www:/var/www/certbot:rw
      - ./certbot/conf:/etc/letsencrypt:rw
    depends_on:
        nginx:
          condition: service_healthy
    networks:
      - bot_network

networks:
  bot_network:
    driver: bridge