events {
    worker_connections 1024;
}

http {
    server {
        listen 80;
        server_name bot.shasero.ru www.bot.shasero.ru;

        # Для проверки домена Certbot
        location /.well-known/acme-challenge/ {
            root /var/www/certbot;
        }

        # Все остальные запросы пока перенаправляем на HTTP-версию бота
        location / {
            proxy_pass http://bot:7111;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}